fix e2e for sbt.

diff --git a/.github/workflows/e2e-cache.yml b/.github/workflows/e2e-cache.yml
--- a/.github/workflows/e2e-cache.yml
+++ b/.github/workflows/e2e-cache.yml
@@ -180,10 +180,30 @@ jobs:
           distribution: 'adopt'
           java-version: '11'
           cache: sbt
-      - name: Confirm that ~/.ivy2/cache directory has been made
+
+      - name: Confirm that ~/Library/Caches/Coursier directory has been made
+        if: matrix.os == 'macos-latest'
         run: |
-          if [ ! -d ~/.ivy2/cache ]; then
-            echo "::error::The ~/.ivy2/cache directory does not exist unexpectedly"
+          if [ ! -d ~/Library/Caches/Coursier ]; then
+            echo "::error::The ~/Library/Caches/Coursier directory does not exist unexpectedly"
             exit 1
           fi
-          ls ~/.ivy2/cache
+          ls ~/Library/Caches/Coursier
+
+      - name: Confirm that ~/AppData/Local/Coursier/Cache directory has been made
+        if: matrix.os == 'windows-latest'
+        run: |
+          if [ ! -d ~/AppData/Local/Coursier/Cache ]; then
+            echo "::error::The ~/AppData/Local/Coursier/Cache directory does not exist unexpectedly"
+            exit 1
+          fi
+          ls ~/AppData/Local/Coursier/Cache
+
+      - name: Confirm that ~/.cache/coursier directory has been made
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          if [ ! -d ~/.cache/coursier ]; then
+            echo "::error::The ~/.cache/coursier directory does not exist unexpectedly"
+            exit 1
+          fi
+          ls ~/.cache/coursier
